import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/context/ThemeProvider";
import Theme from "@/components/Theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <div className="flex justify-center my-5">
            <div className="max-w-5xl w-full flex justify-end">
              <Theme />
            </div>
          </div>

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
